a2lix/TranslationFormBundle

- Locale/DefaultProvider.php
As some magic is done when defining services, I thought it would be helpful to provide some info in the exception that occurs when `a2lix_translation_form.locales` or even when `a2lix_translation_form` is not configured.
> Show more helpful exception message if bundle locales are not configured correctly

- Form/Type/TranslatedEntityType.php
When you have many associations or many locales, TranslatedEntityType do a query for every one. In this way, with inner join translations only do once.
> InnerJoin to improve TranslatedEntityType performance

- Form/Type/TranslationsFormsType.php
- Form/Type/TranslationsType.php
to allow several translation fields on the same form. See #183
> Use a closure for types empty_data

- Resources/views/default.html.twig
- Resources/views/macros.html.twig
Hey!
I'm facing an issue with reusing the twig templte more than one time on the same page. This is due to the `date-target` which is the same one reused for all types. This PR fixes the issue by adding a new class prefixed by the field id. I have also kept the previous class for BC.
> Fix tabs when using the widget more than one time on the same page

- Form/EventListener/TranslationsListener.php
- Form/Type/TranslatedEntityType.php
- Form/Type/TranslationsFieldsType.php
- Form/Type/TranslationsFormsType.php
- Form/Type/TranslationsLocalesSelectorType.php
- Form/Type/TranslationsType.php
- Util/LegacyFormHelper.php
> Symfony 3.0 support

- TranslationForm/TranslationForm.php
Pattern option is also moved to attr (like maxlength), so it should be fixed in this way.
> Fix error in Symfony 3.0, deprecated pattern option in 2.5

- Resources/views/default.html.twig
It seems ironic that in a multi-lingual context, the labels can't be translated.
Locales should not be left not translated.
This PR also include the support for the label attribute (could be defined by explicitly using `TranslationsFieldsType` or via a Form Extension.
> Allow translation labels to be translated

- Resources/views/default.html.twig
This is a follow up on #231, the point is pretty much the same too... We should allow for the "[Default]" label to be translated too.
This PR also include the support for the `default_label` var (in the FormView) to override the translation key (it's very easy to do via a Form Extension on `TranslationsType`, for example, I can provide an example if you wish).
> Allow "default translation" ([Default]) label to be translated

- composer.json
Ref: https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
> Remove unbound version constraints for PHP

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
Adding some PR and issue templates from Sonata directly (with minor adjustements). They work great on sonata bundles and it provides some basic stuff to be able to help people with their issues / PR.
Added license file too.
> Add license and Issue/PR templates

- .travis.yml
- composer.json
I am targeting this branch, because we need Symfony 4 support for 2.x branch.
Closes #277
```markdown
- Added Symfony 4 support for 2.x branch
```
Add Symfony 4 support
> Symfony 4 support for 2.x branch

- .flintci.yml
- .php_cs.dist
- DependencyInjection/A2lixTranslationFormExtension.php
- DependencyInjection/Compiler/LocaleProviderPass.php
- Form/EventListener/TranslationsFormsListener.php
- Form/EventListener/TranslationsListener.php
- Form/Type/TranslatedEntityType.php
- Form/Type/TranslationsFieldsType.php
- Form/Type/TranslationsFormsType.php
- Form/Type/TranslationsLocalesSelectorType.php
- Form/Type/TranslationsType.php
- Locale/DefaultProvider.php
- Resources/config/services.xml
- Tests/DependencyInjection/A2lixTranslationFormExtensionTest.php
- Tests/Gedmo/Fixtures/Entity/Product.php
- Tests/Gedmo/Form/TranslationsTypeTest.php
- Tests/Locale/DefaultProviderTest.php
- Tests/TranslationsTypeTestCase.php
- TranslationForm/TranslationForm.php
- Util/Gedmo/EventListener/LocaleListener.php
- Util/Gedmo/config/gedmo.xml
- Util/LegacyFormHelper.php
I am targeting this branch, because this is pedantinc.
- Added short array syntax, as we have php5.4 as minimum, we can use short array safely.
- Enabled xmllint on flintCI
- Minor code style improvements
All this should improve or minimize merge issues on master
> Use short array, and minor fixed on code styling

- Form/Type/TranslatedEntityType.php
- Form/Type/TranslationsLocalesSelectorType.php
I am targeting this branch, because this is BC.
```markdown
- Usage of FQCNs for form types to improve SF3 compatibility
```
getParent should use FQCNs when possible, to avoid warnings/errors on SF3
> Fix parent form type on SF3

- Resources/config/services.xml
I am targeting this branch, because this is BC.
```markdown
- Remove call to `setRequest` on the xml configuration fixes scope widening
```
it is done on the bundle extension conditionally. Will be "setRequestStack" when RequestStack is available otherwise "setRequest"
> Remove call to setRequest

- UPGRADE-3.0.md
I am targeting this branch, because it's an improvement for 2.0 -> 3.0 upgrade guide.
```markdown
- Improved upgrade guide from 2.0 to 3.0
```
I faced some not documented upgrading issues while upgrading to version 3 of this bundle. I think this upgrade guide improvement will be useful for others.
> Improved upgrade guide

- src/Form/EventListener/TranslationsListener.php
I am targeting this branch, because it fix the issue #320 by removing correctly the KNP empty translations.
Closes #320 
```markdown
Remove correctly the KNP empty translations
```
Use the method `isEmpty()` instead of `empty()` for [KNP translatable](https://github.com/KnpLabs/DoctrineBehaviors#translatable)
> Remove empty KNP translations on form submit

- .travis.yml
- DependencyInjection/Compiler/TemplatingPass.php
- DependencyInjection/Configuration.php
- Form/EventListener/TranslationsListener.php
- Form/Type/TranslatedEntityType.php
- Form/Type/TranslationsFormsType.php
- Locale/DefaultProvider.php
- TranslationForm/TranslationForm.php
I am targeting this branch, because this is BC.
```markdown
- Remove deprecation messages when using `symfony/config ^4.2`
```
This allows using Symfony 4.2 without getting a lot of deprecation messages
> Fix root node deprecations

- src/Form/EventListener/TranslationsFormsListener.php
I am targeting this branch, because {reason}.
Closes #{put_issue_number_here}
```markdown
- Added some `Class::newMethod` to do great stuff
```
> Fix KNP empty translations still persisted 2

- src/Resources/views/macros.html.twig
I am targeting this branch, because it's the branch where the error is located. It's ok in the equivalent file in 2.x branch.
```markdown
- Typo in variable reference
- Rendering the complete form row (label was being omitted)
```
All fields were being rendered, not only those especified in `fieldsNames`.
There's an errata in the rendering (an extra 's' in `translationsFields`).
Also, labels where not being rendered nor row rendering could be customized.
> Translations fields in fieldNames are not being filtered

- src/Resources/views/bootstrap_3_layout.html.twig
- src/Resources/views/macros_bootstrap_3.html.twig
Template allowing compatibility with bootstrap 3 and sonata admin
> Bootstrap 3 compatibility

- src/Resources/views/macros.html.twig
- src/Resources/views/macros_bootstrap_4.html.twig
- src/Resources/views/macros_bootstrap_5.html.twig
With this example we have a conflict id on the tab : 
```
{{ a2lixTranslations.partialTranslations(form.translations, ['name']) }}
...
{{ a2lixTranslations.partialTranslations(form.translations, ['feedbackPositive', 'feedbackNegative']) }}
```
With this PR, we no longer have the same id.
> Fix multiple partial translations

- src/Form/EventListener/TranslationsListener.php
- src/Form/Type/TranslationsType.php
- tests/Form/Type/TranslationsTypeAdvancedTest.php
Tab labels are now translatable / can be tailored.
You may now set labels for each tab by adding a `locale_labels` array to the `TranslationsType` form type, like so:
```php
$form = $this->factory->createBuilder(FormType::class, new Product())
->add('translations', TranslationsType::class, [
'locale_labels' => [
'fr' => 'Français',
'en' => 'English',
],
])
->add('save', SubmitType::class)
->getForm()
;
```
If a label is not set here (in this examplen `de` for instance), its value will default to null and the previous behaviour will kick-in (_the template with capitalize the locale name_).
Hence, this does not introduce any breaking change and no change of defaults, and seems perfectly safe.
As the `trans` filter is used in the templates, you can also use translation keys directly here: …
> Add translatable locale labels (Should fix #262)

- README.md
- composer.json
This PR bumps the dependencies in `composer.json` to allow for Symfony 6.0+
> Allow Symfony 6.0+

- src/Form/EventListener/TranslationsFormsListener.php
- src/Form/EventListener/TranslationsListener.php
I am targeting master because a tag 3.0.11 will be probably needed. And to be honest Iam not sure which branch to target, maybe the version 2 is relevant (but automatic merge was not possible). Let me know how I can help. I think the subject of this PR is very important and Iam ready to follow rules and modify it in order to see it merged. Thank you for your time.
Closes #361
Closes #356
```markdown
Fix form validation for required locales.
Form validation for required locales.
Check if this fix is only relevant when using knp behaviors or if it can be applied globally.
A check is added for required locale when submiting the form, the element is not removed if the locale is required in order to trigger the "NotBlank" constraint. Otherwise, there is no validation (can submit all fields …
```
> :bug: Fix form validation when locale is required (knp behaviors)

- src/Resources/views/bootstrap_4_layout.html.twig
- src/Resources/views/bootstrap_5_layout.html.twig
- src/Resources/views/macros_bootstrap_4.html.twig
- src/Resources/views/macros_bootstrap_5.html.twig
I am targeting this branch, because i don't see these files in 2.x.
Closes #389
```markdown
Replaced `<a href="*">` to `<div data-bs-target="*">`
```
> fix: using href="#*" spams browser history
